export {
  type CoChange,
  type CoChangePair,
  DEFAULT_MAX_FILE_BYTES,
  DEFAULT_MAX_FILES_PER_COMMIT,
  GitError,
  type ImportEdge,
  type IndexedFile,
  type IndexedSymbol,
  type IndexOptions,
  indexRepo,
  type RepoIndex,
  type SourceLanguage,
  type SymbolDef,
  type SymbolKind,
  scrubbedGitEnv,
  type UnresolvedImport,
} from "./index/index.ts";
export {
  buildExport,
  type CitingClaim,
  DroppedFeatureError,
  DuplicateManifestError,
  EmptyStoreError,
  type ExportOptions,
  openStore,
  StaleParentError,
  type Store,
  StoreError,
  UnknownFeatureError,
  UnsupportedSchemaError,
  writeExport,
} from "./store/index.ts";
